name: sso_futurescape
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.68+76

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.



dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^0.1.3
  datetime_picker_formfield: ^1.0.0
  flutter_datetime_picker: ^1.3.8
  introduction_screen: ^1.0.8
  mime: ^0.9.6+3
  intl: ^0.16.1
  intl_phone_number_input: ^0.4.0+2
  flutter_html: ^0.11.1
  flutter_spinkit: ^4.1.2+1
  flutter_google_places: ^0.2.5
  connectivity: ^0.4.8+2
  shared_preferences: ^0.5.8
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
  encrypt: ^4.0.0
  common_config:
    path: './common_config'
  http: ^0.12.1
  toast: ^0.1.5
  #image: 2.1.14
  localstorage: ^3.0.2+5
  firebase_core: ^0.4.4+3
  firebase_database: ^3.1.5
  firebase_messaging: ^6.0.16
  firebase_crashlytics: ^0.1.3+3
  firebase_dynamic_links: ^0.5.0+11
  firebase_remote_config: ^0.3.0+3
  flutter_image_compress: ^0.6.5
  file_picker: ^1.9.0+1
  autocomplete_textfield: ^1.7.3
  libphonenumber: ^1.0.1
  flutter_downloader: ^1.4.4
  carousel_slider: ^2.1.0
  facebook_analytics_plugin: ^0.0.1+8
  facebook_app_events: ^0.6.0
  uni_links: ^0.4.0
  share: ^0.6.5
  permission_handler: ^5.0.0+hotfix.8
  path_provider: ^1.6.10
  package_info: ^0.4.0+17
  image_picker: ^0.6.6+1
  #image: ^2.1.14
  location: ^3.0.2
  google_maps_flutter: ^0.5.28+1
  geocoder: ^0.2.1
  flutter_webview_plugin: ^0.3.11
  flutter_local_notifications: ^1.4.3
  flutter_open_whatsapp: ^0.1.2
  device_info: ^0.4.2+2
  flutter_launch: ^0.2.0
  flutter_email_sender: ^3.0.1
  app_settings: 4.0.3
  appsflyer_sdk: ^5.2.0+2
  photo_view: 0.10.0
  in_app_update: ^1.1.11
  enum_to_string: ^1.0.9
  flutter_phone_direct_caller:
    git:
      url: https://github.com/yanisalfian/flutter-phone-direct-caller.git
  #  call_number: ^0.0.1
  contacts_service: ^0.4.6
  random_color: ^1.0.5
  facebook_deeplinks: ^0.1.0
  flutter_facebook_app_links: ^1.1.0+1
  sqflite: ^1.3.0+2
  #firebase_admob: ^0.9.3+2
  google_fonts: ^1.1.0
  cached_network_image: ^2.2.0+1
  #image: ^2.1.15
  auto_size_text: ^2.1.0
  esys_flutter_share: ^1.0.2
  search_widget: ^1.0.2
  email_validator: ^1.0.5
  fluttertoast: ^4.0.1
  shimmer: ^1.1.1
  getflutter: ^1.0.11
  progress_dialog: ^1.2.4
  easy_localization: ^2.3.2
  #sms: ^0.2.4

  # flutter_advanced_networkimage: ^0.7.0
  flutter_country_picker: ^0.1.6
  image: ^2.0.0
  #photo_view: ^0.9.2
  #app_review: ^2.0.1
  need_resume: ^1.0.4
  uri: ^0.11.3+1
  jitsi_meet: ^0.4.1
  flutter_animator: ^2.1.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


# The following section is specific to Flutter.
flutter:
  assets:
    - lang/en.json
    - lang/zh.json
    - images/location.png
    - images/gate.png
    - images/logo.png
    - images/403-icon.png
    - images/404-icon.png
    - images/500-icon.png
    - images/apple.jpg
    - images/avatar.jpg
    - images/axis-bank.png
    - images/back.jpg
    - images/be.jpg
    - images/bev.jpg
    - images/bg1.jpg
    - images/bg2.jpg
    - images/brand_f.jpg
    - images/building.png
    - images/building1.png
    - images/building-bg.png
    - images/building-bg.svg
    - images/burger-king.png
    - images/camera.png
    - images/cheque.png
    - images/chsone.webp
    - images/complex.png
    - images/credit-card.png
    - images/dash1.png
    - images/dash2.png
    - images/dash3.png
    - images/dash4.png
    - images/dash5.png
    - images/dash6.png
    - images/dash_liquor_shop.png
    - images/pyna.png

    - images/cheque.png
    - images/eft.png
    - images/eft.png
    - images/dash12.png
    - images/dash13.png
    - images/intro_recipe.png


    - images/interest/temp-askneigh.jpg
    - images/interest/temp-bill.jpg
    - images/interest/temp-cab.jpg
    - images/interest/temp-domestic.jpg
    - images/interest/temp-electrician.jpg
    - images/interest/temp-food.jpg
    - images/interest/temp-gatesecurity.jpg
    - images/interest/temp-grocery.jpg
    - images/interest/temp-homecooked.jpg
    - images/interest/temp-knowneigh.jpg
    - images/interest/temp-maintenence.jpg
    - images/interest/temp-petrol.jpg
    - images/interest/temp-realestaterating.jpg
    - images/interest/temp-schoolrating.jpg
    - images/interest/temp-society-rules.jpg
    - images/interest/temp-buysell.png
    - images/intro_restaurant.png
    - images/intro_shopping.png
    - images/intro_society.png
    - images/intro_tiffin.png




    # - images/bg.jpg
    # - images/bg.png

    - images/frozen.jpg
    - images/bev.jpg
    - images/brand_f.jpg
    - images/be.jpg
    - images/dash-bg.jpg
    - images/debit-card.png
    - images/default.png
    - images/default_restaurant.png
    - images/default_tiffin.png
    - images/default_grocery.png


    - images/drive.png
    - images/dummy_logo.png
    - images/dummy_logo-x.png
    - images/dummy_logo-xxx.png
    - images/ecollect.png
    - images/eft.png
    - images/eggs.jpg
    - images/floor.png
    - images/floor1.png
    - images/food-1.jpeg
    - images/frozen.jpg
    - images/gallery.png
    - images/grapes.jpg
    - images/gro.jpg
    - images/groceries.jpg
    - images/grthre.jpg
    - images/grtwo.jpg
    - images/guava.jpg
    - images/hdfc-bank.png
    - images/yes_bank.png
    - images/mobikwik.png
    - images/home.jpg
    - images/homestylefood.png
    - images/icici-bank.png
    - images/in.png

    - images/kiwi.jpg
    - images/kotak-bank.png
    - images/lemons.jpg
    - images/mcd.jpg
    - images/myflats.png
    - images/myvisitors.png
    - images/netbanking.png
    - images/no-connection.png
    - images/no-image.jpg
    - images/nonveg.jpg
    - images/other-bank.png
    - images/out.png
    - images/paymentfailed_icon.png
    - images/paymentsuccess_icon.png
    - images/pending-approval.png
    - images/pineapple.jpg
    - images/play-icon.png
    - images/restaurant_card.jpg
    - images/restaurants.png
    - images/sbi-bank.png
    - images/screen01.jpg
    - images/screen02.jpg
    - images/screen03.jpg
    - images/society_card.jpg
    - images/tiffin_card.jpg
    - images/tomato.jpg
    - images/unit.png
    - images/unit1.png
    - images/veg.jpg
    - images/vesa.webp
    - images/vizlog_card.jpg
    - images/vizlog_icon.webp
    - images/location-pin.png
    - images/afternoon.png
    - images/purpose.png

    - images/inter-home.png
    - images/inter-security.png
    - images/inter-neighbour.png
    - images/inter-food.png
    - images/inter-worker.png
    - images/inter-ride.png

    - images/intro1.png
    - images/intro2.png
    - images/intro3.png
    - images/intro4.png
    - images/intro5.png

    - images/myflatintro1.png
    - images/myflatintro2.png

    - images/restaurantintro1.png
    - images/restaurantintro2.png

    - images/tiffinintro1.png
    - images/tiffinintro2.png

    - images/groceryintro1.png
    - images/groceryintro2.png

    - images/building_white.png

    - images/icon-helpline.png
    - images/icon-donate.png
    - images/icon-ngo.png
    - images/icon-hospital.png
    - images/corona.png
    - images/terms.png
    - images/googlemaps.png
    - images/view_menu.png
    - images/call_now.png
    - images/order_now.png

    - images/covid-awareness.jpg

    - images/slider1.jpeg
    - images/slider2.jpg
    - images/slider3.jpg
    - images/slider4.jpg
    - images/order_success.png
    - images/order_failed.png
    - images/meetingintro1.png
    - images/dash14.png
    - assets/images/
  #    -
  #    - images/default.png
  #    - images/groceries.jpg
  #    - images/grtwo.jpg
  #    - images/grthre.jpg
  #    - images/veg.jpg
  #    - images/complex.png
  #    - images/building.png
  #    - images/dummy_logo.png
  #    - images/floor.png
  #    - images/unit.png
  #    - images/pending-approval.png
  #    - images/no-connection.png
  #    - images/paymentfailed_icon.png
  #    - images/paymentsuccess_icon.png
  #    - images/403-icon.png
  #    - images/404-icon.png
  #    - images/500-icon.png
  #    - images/screen01.jpg
  #    - images/screen02.jpg
  #    - images/screen03.jpg
  #
  #    - images/dash-bg.jpg
  #    - images/myflats.png
  #    - images/myvisitors.png
  #    - images/restaurants.png
  #    - images/homestylefood.png
  #    - images/default_restaurant.jpg
  #    - images/default_tiffin.jpg
  #
  #
  #    - images/dash1.png
  #    - images/dash2.png
  #    - images/dash3.png
  #    - images/dash4.png
  #
  #
  #
  #
  #
  #
  #    # - images/bg.jpg
  #    # - images/bg.png
  #
  #    - images/frozen.jpg
  #    - images/bev.jpg
  #    - images/brand_f.jpg
  #    - images/be.jpg
  #    - images/eggs.jpg
  #    - images/home.jpg
  #    - images/nonveg.jpg
  #    - images/apple.jpg
  #    - images/grapes.jpg
  #    - images/guava.jpg
  #    - images/kiwi.jpg
  #    - images/lemons.jpg
  #    - images/pineapple.jpg
  #    - images/tomato.jpg
  #    - images/gro.jpg
  #    - images/vesa.webp
  #    - images/chsone.webp
  #    - images/vizlog_icon.webp
  #    - images/restaurant_card.jpg
  #    - images/society_card.jpg
  #    - images/vizlog_card.jpg
  #    - images/tiffin_card.jpg
  #    - images/burger-king.png
  #    - images/mcd.jpg
  #    - images/avatar.jpg
  #    - images/in.png
  #    - images/out.png
  #    - images/building-bg.png


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: FlutterIcon
      fonts:
        - asset: fonts/flutterIcon.ttf
    - family: Roboto-Light
      fonts:
        - asset: fonts/Roboto-Light.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Roboto-Medium
      fonts:
        - asset: fonts/Roboto-Medium.ttf
    - family: Roboto-Bold
      fonts:
        - asset: fonts/Roboto-Bold.ttf

    - family: Gilroy-Regular
      fonts:
        - asset: fonts/Gilroy-Regular.otf
    - family: Gilroy-SemiBold
      fonts:
        - asset: fonts/Gilroy-SemiBold.otf
    - family: Gilroy-Bold
      fonts:
        - asset: fonts/Gilroy-Bold.otf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-Black.ttf
          weight: 900
    - family: RobotoCondensed
      fonts:
        - asset: fonts/RobotoCondensed-Regular.ttf
        - asset: fonts/RobotoCondensed-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
