import 'package:flutter/material.dart';
/// Flutter icons FlutterIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterIcon
///      fonts:
///       - asset: fonts/FlutterIcon.ttf
///
///
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FlutterIcon {

  FlutterIcon._();

  static Map map = {};

  static getCurrencyIcons(int abc) {
    //const IconData rupee = const IconData(0xf156, fontFamily: _kFontFam);
    /*map["rupee"]=const IconData(0xf156, fontFamily: _kFontFam);
    map["rupee"]=const IconData(0xf156, fontFamily: _kFontFam);*/
    return IconData(abc, fontFamily: _kFontFam);
  }

  static const IconData cancel_circled2 = const IconData(
      0xebcb, fontFamily: _kFontFam);
  static const IconData food = const IconData(0xf0f5, fontFamily: _kFontFam);
  static const IconData share = IconData(59405, fontFamily: "MaterialIcons");
  static const IconData doc_text = const IconData(
      0xf0f6, fontFamily: _kFontFam);

  static const IconData arrows_cw = const IconData(
      0xec1a, fontFamily: _kFontFam);
  static const IconData cw = const IconData(0xec18, fontFamily: _kFontFam);
  static const IconData left_open = const IconData(
      0xec0d, fontFamily: _kFontFam);

  static const _kFontFam = 'FlutterIcon';
  static const IconData right_open = const IconData(
      0xec0e, fontFamily: _kFontFam);
  static const IconData rupee = const IconData(0xf156, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(
      0xf09a, fontFamily: _kFontFam);
  static const IconData google = const IconData(0xf1a0, fontFamily: _kFontFam);
  static const IconData right_big = const IconData(
      0xec12, fontFamily: _kFontFam);
  static const IconData bell = const IconData(0xebea, fontFamily: _kFontFam);
  static const IconData user_1 = const IconData(0xebbc, fontFamily: _kFontFam);
  static const IconData users_1 = const IconData(0xebbd, fontFamily: _kFontFam);
  static const IconData phone_1 = const IconData(0xebf2, fontFamily: _kFontFam);
  static const IconData mail_alt = const IconData(
      0xf0e0, fontFamily: _kFontFam);
  static const IconData globe = const IconData(0xec2b, fontFamily: _kFontFam);
  static const IconData ok_circled = const IconData(
      0xebc7, fontFamily: _kFontFam);
  static const IconData ok_circled2 = const IconData(
      0xebc8, fontFamily: _kFontFam);
  static const IconData attention = const IconData(
      0xebeb, fontFamily: _kFontFam);
  static const IconData edit_1 = const IconData(0xebe5, fontFamily: _kFontFam);
  static const IconData home = const IconData(
      59530, fontFamily: 'MaterialIcons');
  static const IconData angle_left = const IconData(
      0xf104, fontFamily: _kFontFam);
  static const IconData angle_right = const IconData(
      0xf105, fontFamily: _kFontFam);
  static const IconData building = const IconData(
      0xf0f7, fontFamily: _kFontFam);
  static const IconData search_1 = const IconData(
      0xebb5, fontFamily: _kFontFam);
  static const IconData instagram = const IconData(
      0xf16d, fontFamily: _kFontFam);
  static const IconData facebook_official = const IconData(
      0xf230, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xf099, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(
      0xebf7, fontFamily: _kFontFam);
  static const IconData eyedropper = const IconData(
      0xf1fb, fontFamily: _kFontFam);
  static const IconData graduation_cap = const IconData(
      0xf19d, fontFamily: _kFontFam);
  static const IconData pencil_1 = const IconData(
      0xebe4, fontFamily: _kFontFam);
  static const IconData location_1 = const IconData(
      0xebed, fontFamily: _kFontFam);
  static const IconData upload_1 = const IconData(
      0xebe1, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xebf9, fontFamily: _kFontFam);
  static const IconData key = const IconData(0xec50, fontFamily: _kFontFam);
  static const IconData exchange = const IconData(
      0xf0ec, fontFamily: _kFontFam);
  static const IconData ok = const IconData(0xebc6, fontFamily: _kFontFam);
  static const IconData cancel_1 = const IconData(
      0xebc9, fontFamily: _kFontFam);
  static const IconData circle = const IconData(0xf111, fontFamily: _kFontFam);
  static const IconData user_plus = const IconData(
      0xf234, fontFamily: _kFontFam);
  static const IconData chat_empty = const IconData(
      0xf0e6, fontFamily: _kFontFam);
  static const IconData chat_1 = const IconData(0xebe9, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xebcc, fontFamily: _kFontFam);
  static const IconData paper_plane = const IconData(
      0xf1d8, fontFamily: _kFontFam);
  static const IconData paper_plane_empty = const IconData(
      0xf1d9, fontFamily: _kFontFam);
  static const IconData download_1 = const IconData(
      0xebe0, fontFamily: _kFontFam);
  static const IconData eye_1 = const IconData(0xebd8, fontFamily: _kFontFam);
  static const IconData info_circled = const IconData(
      0xebd1, fontFamily: _kFontFam);
  static const IconData share_1 = const IconData(0xf1e0, fontFamily: _kFontFam);
  static const IconData file_code = const IconData(
      0xf1c9, fontFamily: _kFontFam);
  static const IconData doc = const IconData(0xebef, fontFamily: _kFontFam);
  static const IconData docs = const IconData(0xf0c5, fontFamily: _kFontFam);
  static const IconData print_1 = const IconData(0xebe6, fontFamily: _kFontFam);
  static const IconData th_large = const IconData(
      0xebc3, fontFamily: _kFontFam);
  static const IconData down = const IconData(0xf175, fontFamily: _kFontFam);
  static const IconData up = const IconData(0xf176, fontFamily: _kFontFam);
  static const IconData left = const IconData(0xf177, fontFamily: _kFontFam);
  static const IconData right = const IconData(0xf178, fontFamily: _kFontFam);

  static const IconData ellipsis_vert = const IconData(
      0xf142, fontFamily: _kFontFam);
  static const IconData shopping_bag = const IconData(
      0xf290, fontFamily: _kFontFam);
  static const IconData shopping_basket = const IconData(
      0xf291, fontFamily: _kFontFam);
  static const IconData clock_1 = const IconData(0xebfe, fontFamily: _kFontFam);
  static const IconData whatsapp =
      const IconData(0xf232, fontFamily: _kFontFam);
  static const IconData calendar_times_o =
      const IconData(0xf273, fontFamily: _kFontFam);
  static const IconData help_1 = const IconData(0xf128, fontFamily: _kFontFam);

  static const IconData angle_up =
      const IconData(0xf106, fontFamily: _kFontFam);
  static const IconData angle_down =
      const IconData(0xf107, fontFamily: _kFontFam);
  static const IconData minus_squared_alt =
      const IconData(0xf147, fontFamily: _kFontFam);
  static const IconData minus = const IconData(0xebce, fontFamily: _kFontFam);

// static const IconData truck = const IconData(0xec51, fontFamily: _kFontFam);
// static const IconData hammer = const IconData(0xec52, fontFamily: _kFontFam);
// static const IconData lemon = const IconData(0xec53, fontFamily: _kFontFam);
// static const IconData move_1 = const IconData(0xf047, fontFamily: _kFontFam);
// static const IconData link_ext = const IconData(0xf08e, fontFamily: _kFontFam);
// static const IconData check_empty = const IconData(0xf096, fontFamily: _kFontFam);
// static const IconData bookmark_empty = const IconData(0xf097, fontFamily: _kFontFam);
// static const IconData phone_squared = const IconData(0xf098, fontFamily: _kFontFam);

// static const IconData github_circled = const IconData(0xf09b, fontFamily: _kFontFam);
// static const IconData rss = const IconData(0xf09e, fontFamily: _kFontFam);
// static const IconData hdd = const IconData(0xf0a0, fontFamily: _kFontFam);
// static const IconData certificate = const IconData(0xf0a3, fontFamily: _kFontFam);
// static const IconData left_circled = const IconData(0xf0a8, fontFamily: _kFontFam);
// static const IconData right_circled = const IconData(0xf0a9, fontFamily: _kFontFam);
// static const IconData up_circled = const IconData(0xf0aa, fontFamily: _kFontFam);
// static const IconData down_circled = const IconData(0xf0ab, fontFamily: _kFontFam);
// static const IconData tasks = const IconData(0xf0ae, fontFamily: _kFontFam);
// static const IconData filter_1 = const IconData(0xf0b0, fontFamily: _kFontFam);
// static const IconData resize_full_alt = const IconData(0xf0b2, fontFamily: _kFontFam);
// static const IconData beaker = const IconData(0xf0c3, fontFamily: _kFontFam);
// static const IconData docs = const IconData(0xf0c5, fontFamily: _kFontFam);
// static const IconData blank = const IconData(0xf0c8, fontFamily: _kFontFam);
// static const IconData menu_1 = const IconData(0xf0c9, fontFamily: _kFontFam);
  static const IconData list_bullet = const IconData(
      0xf0ca, fontFamily: _kFontFam);

// static const IconData list_numbered = const IconData(0xf0cb, fontFamily: _kFontFam);
// static const IconData strike = const IconData(0xf0cc, fontFamily: _kFontFam);
// static const IconData underline_1 = const IconData(0xf0cd, fontFamily: _kFontFam);
// static const IconData table = const IconData(0xf0ce, fontFamily: _kFontFam);
// static const IconData magic = const IconData(0xf0d0, fontFamily: _kFontFam);
// static const IconData pinterest_circled = const IconData(0xf0d2, fontFamily: _kFontFam);
// static const IconData pinterest_squared = const IconData(0xf0d3, fontFamily: _kFontFam);
// static const IconData gplus_squared = const IconData(0xf0d4, fontFamily: _kFontFam);
// static const IconData gplus = const IconData(0xf0d5, fontFamily: _kFontFam);
// static const IconData money = const IconData(0xf0d6, fontFamily: _kFontFam);
// static const IconData columns = const IconData(0xf0db, fontFamily: _kFontFam);
// static const IconData sort_1 = const IconData(0xf0dc, fontFamily: _kFontFam);
// static const IconData sort_down = const IconData(0xf0dd, fontFamily: _kFontFam);
// static const IconData sort_up = const IconData(0xf0de, fontFamily: _kFontFam);

// static const IconData linkedin = const IconData(0xf0e1, fontFamily: _kFontFam);
// static const IconData gauge = const IconData(0xf0e4, fontFamily: _kFontFam);
// static const IconData comment_empty = const IconData(0xf0e5, fontFamily: _kFontFam);
// static const IconData chat_empty = const IconData(0xf0e6, fontFamily: _kFontFam);
// static const IconData sitemap = const IconData(0xf0e8, fontFamily: _kFontFam);
// static const IconData paste = const IconData(0xf0ea, fontFamily: _kFontFam);
// static const IconData lightbulb = const IconData(0xf0eb, fontFamily: _kFontFam);

// static const IconData download_cloud = const IconData(0xf0ed, fontFamily: _kFontFam);
// static const IconData upload_cloud = const IconData(0xf0ee, fontFamily: _kFontFam);
// static const IconData user_md = const IconData(0xf0f0, fontFamily: _kFontFam);
// static const IconData stethoscope = const IconData(0xf0f1, fontFamily: _kFontFam);
// static const IconData suitcase = const IconData(0xf0f2, fontFamily: _kFontFam);
// static const IconData bell_alt = const IconData(0xf0f3, fontFamily: _kFontFam);
// static const IconData coffee = const IconData(0xf0f4, fontFamily: _kFontFam);
// static const IconData food = const IconData(0xf0f5, fontFamily: _kFontFam);
// static const IconData doc_text = const IconData(0xf0f6, fontFamily: _kFontFam);

// static const IconData hospital = const IconData(0xf0f8, fontFamily: _kFontFam);
// static const IconData ambulance = const IconData(0xf0f9, fontFamily: _kFontFam);
// static const IconData medkit = const IconData(0xf0fa, fontFamily: _kFontFam);
// static const IconData fighter_jet = const IconData(0xf0fb, fontFamily: _kFontFam);
// static const IconData beer = const IconData(0xf0fc, fontFamily: _kFontFam);
// static const IconData h_sigh = const IconData(0xf0fd, fontFamily: _kFontFam);
// static const IconData plus_squared = const IconData(0xf0fe, fontFamily: _kFontFam);
// static const IconData angle_double_left = const IconData(0xf100, fontFamily: _kFontFam);
// static const IconData angle_double_right = const IconData(0xf101, fontFamily: _kFontFam);
// static const IconData angle_double_up = const IconData(0xf102, fontFamily: _kFontFam);
// static const IconData angle_double_down = const IconData(0xf103, fontFamily: _kFontFam);
//
//
// static const IconData angle_up = const IconData(0xf106, fontFamily: _kFontFam);
// static const IconData angle_down = const IconData(0xf107, fontFamily: _kFontFam);
// static const IconData desktop = const IconData(0xf108, fontFamily: _kFontFam);
// static const IconData laptop_1 = const IconData(0xf109, fontFamily: _kFontFam);
// static const IconData tablet_1 = const IconData(0xf10a, fontFamily: _kFontFam);
// static const IconData mobile = const IconData(0xf10b, fontFamily: _kFontFam);
// static const IconData circle_empty = const IconData(0xf10c, fontFamily: _kFontFam);
// static const IconData quote_left = const IconData(0xf10d, fontFamily: _kFontFam);
// static const IconData quote_right = const IconData(0xf10e, fontFamily: _kFontFam);
// static const IconData spinner = const IconData(0xf110, fontFamily: _kFontFam);

// static const IconData reply_2 = const IconData(0xf112, fontFamily: _kFontFam);
// static const IconData github = const IconData(0xf113, fontFamily: _kFontFam);
// static const IconData folder_empty = const IconData(0xf114, fontFamily: _kFontFam);
// static const IconData folder_open_empty = const IconData(0xf115, fontFamily: _kFontFam);
// static const IconData smile_1 = const IconData(0xf118, fontFamily: _kFontFam);
// static const IconData frown = const IconData(0xf119, fontFamily: _kFontFam);
// static const IconData meh = const IconData(0xf11a, fontFamily: _kFontFam);
// static const IconData gamepad_1 = const IconData(0xf11b, fontFamily: _kFontFam);
// static const IconData keyboard_1 = const IconData(0xf11c, fontFamily: _kFontFam);
// static const IconData flag_empty = const IconData(0xf11d, fontFamily: _kFontFam);
// static const IconData flag_checkered = const IconData(0xf11e, fontFamily: _kFontFam);
// static const IconData terminal = const IconData(0xf120, fontFamily: _kFontFam);
// static const IconData code_1 = const IconData(0xf121, fontFamily: _kFontFam);
// static const IconData reply_all = const IconData(0xf122, fontFamily: _kFontFam);
// static const IconData star_half_alt = const IconData(0xf123, fontFamily: _kFontFam);
// static const IconData direction = const IconData(0xf124, fontFamily: _kFontFam);
// static const IconData crop_1 = const IconData(0xf125, fontFamily: _kFontFam);
// static const IconData fork = const IconData(0xf126, fontFamily: _kFontFam);
// static const IconData unlink_1 = const IconData(0xf127, fontFamily: _kFontFam);
// static const IconData help_1 = const IconData(0xf128, fontFamily: _kFontFam);
// static const IconData info_1 = const IconData(0xf129, fontFamily: _kFontFam);
// static const IconData attention_alt = const IconData(0xf12a, fontFamily: _kFontFam);
// static const IconData superscript = const IconData(0xf12b, fontFamily: _kFontFam);
// static const IconData subscript = const IconData(0xf12c, fontFamily: _kFontFam);
// static const IconData eraser = const IconData(0xf12d, fontFamily: _kFontFam);
// static const IconData puzzle = const IconData(0xf12e, fontFamily: _kFontFam);
// static const IconData mic_1 = const IconData(0xf130, fontFamily: _kFontFam);
// static const IconData mute = const IconData(0xf131, fontFamily: _kFontFam);
// static const IconData shield = const IconData(0xf132, fontFamily: _kFontFam);
// static const IconData calendar_empty = const IconData(0xf133, fontFamily: _kFontFam);
// static const IconData extinguisher = const IconData(0xf134, fontFamily: _kFontFam);
// static const IconData rocket_1 = const IconData(0xf135, fontFamily: _kFontFam);
// static const IconData maxcdn = const IconData(0xf136, fontFamily: _kFontFam);
// static const IconData angle_circled_left = const IconData(0xf137, fontFamily: _kFontFam);
// static const IconData angle_circled_right = const IconData(0xf138, fontFamily: _kFontFam);
// static const IconData angle_circled_up = const IconData(0xf139, fontFamily: _kFontFam);
// static const IconData angle_circled_down = const IconData(0xf13a, fontFamily: _kFontFam);
// static const IconData html5 = const IconData(0xf13b, fontFamily: _kFontFam);
// static const IconData css3 = const IconData(0xf13c, fontFamily: _kFontFam);
// static const IconData anchor = const IconData(0xf13d, fontFamily: _kFontFam);
// static const IconData lock_open_alt = const IconData(0xf13e, fontFamily: _kFontFam);
// static const IconData bullseye = const IconData(0xf140, fontFamily: _kFontFam);
// static const IconData ellipsis = const IconData(0xf141, fontFamily: _kFontFam);
// static const IconData ellipsis_vert = const IconData(0xf142, fontFamily: _kFontFam);
// static const IconData rss_squared = const IconData(0xf143, fontFamily: _kFontFam);
// static const IconData play_circled = const IconData(0xf144, fontFamily: _kFontFam);
// static const IconData ticket = const IconData(0xf145, fontFamily: _kFontFam);
// static const IconData minus_squared = const IconData(0xf146, fontFamily: _kFontFam);
// static const IconData minus_squared_alt = const IconData(0xf147, fontFamily: _kFontFam);
// static const IconData level_up = const IconData(0xf148, fontFamily: _kFontFam);
// static const IconData level_down = const IconData(0xf149, fontFamily: _kFontFam);
// static const IconData ok_squared = const IconData(0xf14a, fontFamily: _kFontFam);
// static const IconData pencil_squared = const IconData(0xf14b, fontFamily: _kFontFam);
// static const IconData link_ext_alt = const IconData(0xf14c, fontFamily: _kFontFam);
// static const IconData export_alt = const IconData(0xf14d, fontFamily: _kFontFam);
// static const IconData compass = const IconData(0xf14e, fontFamily: _kFontFam);
// static const IconData expand = const IconData(0xf150, fontFamily: _kFontFam);
// static const IconData collapse = const IconData(0xf151, fontFamily: _kFontFam);
// static const IconData expand_right = const IconData(0xf152, fontFamily: _kFontFam);
// static const IconData euro = const IconData(0xf153, fontFamily: _kFontFam);
// static const IconData pound = const IconData(0xf154, fontFamily: _kFontFam);
// static const IconData dollar = const IconData(0xf155, fontFamily: _kFontFam);

// static const IconData yen = const IconData(0xf157, fontFamily: _kFontFam);
// static const IconData rouble = const IconData(0xf158, fontFamily: _kFontFam);
// static const IconData won = const IconData(0xf159, fontFamily: _kFontFam);
// static const IconData bitcoin = const IconData(0xf15a, fontFamily: _kFontFam);
// static const IconData doc_inv = const IconData(0xf15b, fontFamily: _kFontFam);
// static const IconData doc_text_inv = const IconData(0xf15c, fontFamily: _kFontFam);
// static const IconData sort_name_up = const IconData(0xf15d, fontFamily: _kFontFam);
// static const IconData sort_name_down = const IconData(0xf15e, fontFamily: _kFontFam);
// static const IconData sort_alt_up = const IconData(0xf160, fontFamily: _kFontFam);
// static const IconData sort_alt_down = const IconData(0xf161, fontFamily: _kFontFam);
// static const IconData sort_number_up = const IconData(0xf162, fontFamily: _kFontFam);
// static const IconData sort_number_down = const IconData(0xf163, fontFamily: _kFontFam);
// static const IconData thumbs_up_alt = const IconData(0xf164, fontFamily: _kFontFam);
// static const IconData thumbs_down_alt = const IconData(0xf165, fontFamily: _kFontFam);
// static const IconData youtube_squared = const IconData(0xf166, fontFamily: _kFontFam);
// static const IconData youtube = const IconData(0xf167, fontFamily: _kFontFam);
// static const IconData xing = const IconData(0xf168, fontFamily: _kFontFam);
// static const IconData xing_squared = const IconData(0xf169, fontFamily: _kFontFam);
// static const IconData youtube_play = const IconData(0xf16a, fontFamily: _kFontFam);
// static const IconData dropbox = const IconData(0xf16b, fontFamily: _kFontFam);
// static const IconData stackoverflow = const IconData(0xf16c, fontFamily: _kFontFam);
// static const IconData flickr = const IconData(0xf16e, fontFamily: _kFontFam);
// static const IconData adn = const IconData(0xf170, fontFamily: _kFontFam);
// static const IconData bitbucket = const IconData(0xf171, fontFamily: _kFontFam);
// static const IconData bitbucket_squared = const IconData(0xf172, fontFamily: _kFontFam);
// static const IconData tumblr = const IconData(0xf173, fontFamily: _kFontFam);
// static const IconData tumblr_squared = const IconData(0xf174, fontFamily: _kFontFam);
// static const IconData down = const IconData(0xf175, fontFamily: _kFontFam);
// static const IconData up = const IconData(0xf176, fontFamily: _kFontFam);
// static const IconData left = const IconData(0xf177, fontFamily: _kFontFam);
// static const IconData right = const IconData(0xf178, fontFamily: _kFontFam);
// static const IconData apple = const IconData(0xf179, fontFamily: _kFontFam);
// static const IconData windows = const IconData(0xf17a, fontFamily: _kFontFam);
// static const IconData android_1 = const IconData(0xf17b, fontFamily: _kFontFam);
// static const IconData linux = const IconData(0xf17c, fontFamily: _kFontFam);
// static const IconData dribbble = const IconData(0xf17d, fontFamily: _kFontFam);
// static const IconData skype = const IconData(0xf17e, fontFamily: _kFontFam);
// static const IconData foursquare = const IconData(0xf180, fontFamily: _kFontFam);
// static const IconData trello = const IconData(0xf181, fontFamily: _kFontFam);
// static const IconData female = const IconData(0xf182, fontFamily: _kFontFam);
// static const IconData male = const IconData(0xf183, fontFamily: _kFontFam);
// static const IconData gittip = const IconData(0xf184, fontFamily: _kFontFam);
// static const IconData sun_1 = const IconData(0xf185, fontFamily: _kFontFam);
// static const IconData moon_1 = const IconData(0xf186, fontFamily: _kFontFam);
// static const IconData box = const IconData(0xf187, fontFamily: _kFontFam);
// static const IconData bug_1 = const IconData(0xf188, fontFamily: _kFontFam);
// static const IconData vkontakte = const IconData(0xf189, fontFamily: _kFontFam);
// static const IconData weibo = const IconData(0xf18a, fontFamily: _kFontFam);
// static const IconData renren = const IconData(0xf18b, fontFamily: _kFontFam);
// static const IconData pagelines = const IconData(0xf18c, fontFamily: _kFontFam);
// static const IconData stackexchange = const IconData(0xf18d, fontFamily: _kFontFam);
// static const IconData right_circled2 = const IconData(0xf18e, fontFamily: _kFontFam);
// static const IconData left_circled2 = const IconData(0xf190, fontFamily: _kFontFam);
// static const IconData collapse_left = const IconData(0xf191, fontFamily: _kFontFam);
// static const IconData dot_circled = const IconData(0xf192, fontFamily: _kFontFam);
// static const IconData wheelchair_1 = const IconData(0xf193, fontFamily: _kFontFam);
// static const IconData vimeo_squared = const IconData(0xf194, fontFamily: _kFontFam);
// static const IconData try_icon = const IconData(0xf195, fontFamily: _kFontFam);
// static const IconData plus_squared_alt = const IconData(0xf196, fontFamily: _kFontFam);
// static const IconData space_shuttle = const IconData(0xf197, fontFamily: _kFontFam);
// static const IconData slack = const IconData(0xf198, fontFamily: _kFontFam);
// static const IconData mail_squared = const IconData(0xf199, fontFamily: _kFontFam);
// static const IconData wordpress = const IconData(0xf19a, fontFamily: _kFontFam);
// static const IconData openid = const IconData(0xf19b, fontFamily: _kFontFam);
// static const IconData bank = const IconData(0xf19c, fontFamily: _kFontFam);
// static const IconData graduation_cap = const IconData(0xf19d, fontFamily: _kFontFam);
// static const IconData yahoo = const IconData(0xf19e, fontFamily: _kFontFam);

// static const IconData reddit = const IconData(0xf1a1, fontFamily: _kFontFam);
// static const IconData reddit_squared = const IconData(0xf1a2, fontFamily: _kFontFam);
// static const IconData stumbleupon_circled = const IconData(0xf1a3, fontFamily: _kFontFam);
// static const IconData stumbleupon = const IconData(0xf1a4, fontFamily: _kFontFam);
// static const IconData delicious = const IconData(0xf1a5, fontFamily: _kFontFam);
// static const IconData digg = const IconData(0xf1a6, fontFamily: _kFontFam);
// static const IconData pied_piper_squared = const IconData(0xf1a7, fontFamily: _kFontFam);
// static const IconData pied_piper_alt = const IconData(0xf1a8, fontFamily: _kFontFam);
// static const IconData drupal = const IconData(0xf1a9, fontFamily: _kFontFam);
// static const IconData joomla = const IconData(0xf1aa, fontFamily: _kFontFam);
// static const IconData language_1 = const IconData(0xf1ab, fontFamily: _kFontFam);
// static const IconData fax = const IconData(0xf1ac, fontFamily: _kFontFam);
// static const IconData building_filled = const IconData(0xf1ad, fontFamily: _kFontFam);
// static const IconData child = const IconData(0xf1ae, fontFamily: _kFontFam);
// static const IconData paw_1 = const IconData(0xf1b0, fontFamily: _kFontFam);
// static const IconData spoon = const IconData(0xf1b1, fontFamily: _kFontFam);
// static const IconData cube = const IconData(0xf1b2, fontFamily: _kFontFam);
// static const IconData cubes = const IconData(0xf1b3, fontFamily: _kFontFam);
// static const IconData behance = const IconData(0xf1b4, fontFamily: _kFontFam);
// static const IconData behance_squared = const IconData(0xf1b5, fontFamily: _kFontFam);
// static const IconData steam = const IconData(0xf1b6, fontFamily: _kFontFam);
// static const IconData steam_squared = const IconData(0xf1b7, fontFamily: _kFontFam);
// static const IconData recycle = const IconData(0xf1b8, fontFamily: _kFontFam);
// static const IconData cab = const IconData(0xf1b9, fontFamily: _kFontFam);
// static const IconData taxi = const IconData(0xf1ba, fontFamily: _kFontFam);
// static const IconData tree = const IconData(0xf1bb, fontFamily: _kFontFam);
// static const IconData spotify = const IconData(0xf1bc, fontFamily: _kFontFam);
// static const IconData deviantart = const IconData(0xf1bd, fontFamily: _kFontFam);
// static const IconData soundcloud = const IconData(0xf1be, fontFamily: _kFontFam);
// static const IconData database_1 = const IconData(0xf1c0, fontFamily: _kFontFam);
// static const IconData file_pdf = const IconData(0xf1c1, fontFamily: _kFontFam);
// static const IconData file_word = const IconData(0xf1c2, fontFamily: _kFontFam);
// static const IconData file_excel = const IconData(0xf1c3, fontFamily: _kFontFam);
// static const IconData file_powerpoint = const IconData(0xf1c4, fontFamily: _kFontFam);
// static const IconData file_image = const IconData(0xf1c5, fontFamily: _kFontFam);
// static const IconData file_archive = const IconData(0xf1c6, fontFamily: _kFontFam);
// static const IconData file_audio = const IconData(0xf1c7, fontFamily: _kFontFam);
// static const IconData file_video = const IconData(0xf1c8, fontFamily: _kFontFam);
// static const IconData file_code = const IconData(0xf1c9, fontFamily: _kFontFam);
// static const IconData vine = const IconData(0xf1ca, fontFamily: _kFontFam);
// static const IconData codeopen = const IconData(0xf1cb, fontFamily: _kFontFam);
// static const IconData jsfiddle = const IconData(0xf1cc, fontFamily: _kFontFam);
// static const IconData lifebuoy = const IconData(0xf1cd, fontFamily: _kFontFam);
// static const IconData circle_notch = const IconData(0xf1ce, fontFamily: _kFontFam);
// static const IconData rebel = const IconData(0xf1d0, fontFamily: _kFontFam);
// static const IconData empire = const IconData(0xf1d1, fontFamily: _kFontFam);
// static const IconData git_squared = const IconData(0xf1d2, fontFamily: _kFontFam);
// static const IconData git = const IconData(0xf1d3, fontFamily: _kFontFam);
// static const IconData hacker_news = const IconData(0xf1d4, fontFamily: _kFontFam);
// static const IconData tencent_weibo = const IconData(0xf1d5, fontFamily: _kFontFam);
// static const IconData qq = const IconData(0xf1d6, fontFamily: _kFontFam);
// static const IconData wechat = const IconData(0xf1d7, fontFamily: _kFontFam);
// static const IconData paper_plane = const IconData(0xf1d8, fontFamily: _kFontFam);
//static const IconData paper_plane_empty =  const IconData(0xf1d9, fontFamily: _kFontFam);
// static const IconData history_1 = const IconData(0xf1da, fontFamily: _kFontFam);
// static const IconData circle_thin = const IconData(0xf1db, fontFamily: _kFontFam);
// static const IconData header = const IconData(0xf1dc, fontFamily: _kFontFam);
// static const IconData paragraph = const IconData(0xf1dd, fontFamily: _kFontFam);
// static const IconData sliders = const IconData(0xf1de, fontFamily: _kFontFam);
// static const IconData share_1 = const IconData(0xf1e0, fontFamily: _kFontFam);
// static const IconData share_squared = const IconData(0xf1e1, fontFamily: _kFontFam);
// static const IconData bomb = const IconData(0xf1e2, fontFamily: _kFontFam);
// static const IconData soccer_ball = const IconData(0xf1e3, fontFamily: _kFontFam);
// static const IconData tty = const IconData(0xf1e4, fontFamily: _kFontFam);
// static const IconData binoculars = const IconData(0xf1e5, fontFamily: _kFontFam);
// static const IconData plug = const IconData(0xf1e6, fontFamily: _kFontFam);
// static const IconData slideshare = const IconData(0xf1e7, fontFamily: _kFontFam);
// static const IconData twitch = const IconData(0xf1e8, fontFamily: _kFontFam);
// static const IconData yelp = const IconData(0xf1e9, fontFamily: _kFontFam);
// static const IconData newspaper = const IconData(0xf1ea, fontFamily: _kFontFam);
// static const IconData wifi_1 = const IconData(0xf1eb, fontFamily: _kFontFam);
// static const IconData calc = const IconData(0xf1ec, fontFamily: _kFontFam);
// static const IconData paypal = const IconData(0xf1ed, fontFamily: _kFontFam);
// static const IconData gwallet = const IconData(0xf1ee, fontFamily: _kFontFam);
// static const IconData cc_visa = const IconData(0xf1f0, fontFamily: _kFontFam);
// static const IconData cc_mastercard = const IconData(0xf1f1, fontFamily: _kFontFam);
// static const IconData cc_discover = const IconData(0xf1f2, fontFamily: _kFontFam);
// static const IconData cc_amex = const IconData(0xf1f3, fontFamily: _kFontFam);
// static const IconData cc_paypal = const IconData(0xf1f4, fontFamily: _kFontFam);
// static const IconData cc_stripe = const IconData(0xf1f5, fontFamily: _kFontFam);
// static const IconData bell_off = const IconData(0xf1f6, fontFamily: _kFontFam);
// static const IconData bell_off_empty = const IconData(0xf1f7, fontFamily: _kFontFam);
// static const IconData trash_1 = const IconData(0xf1f8, fontFamily: _kFontFam);
// static const IconData copyright_1 = const IconData(0xf1f9, fontFamily: _kFontFam);
// static const IconData at = const IconData(0xf1fa, fontFamily: _kFontFam);
// static const IconData eyedropper = const IconData(0xf1fb, fontFamily: _kFontFam);
// static const IconData brush_1 = const IconData(0xf1fc, fontFamily: _kFontFam);
// static const IconData birthday = const IconData(0xf1fd, fontFamily: _kFontFam);
// static const IconData chart_area = const IconData(0xf1fe, fontFamily: _kFontFam);
// static const IconData chart_pie = const IconData(0xf200, fontFamily: _kFontFam);
// static const IconData chart_line = const IconData(0xf201, fontFamily: _kFontFam);
// static const IconData lastfm = const IconData(0xf202, fontFamily: _kFontFam);
// static const IconData lastfm_squared = const IconData(0xf203, fontFamily: _kFontFam);
// static const IconData toggle_off = const IconData(0xf204, fontFamily: _kFontFam);
// static const IconData toggle_on = const IconData(0xf205, fontFamily: _kFontFam);
// static const IconData bicycle_1 = const IconData(0xf206, fontFamily: _kFontFam);
// static const IconData bus_1 = const IconData(0xf207, fontFamily: _kFontFam);
// static const IconData ioxhost = const IconData(0xf208, fontFamily: _kFontFam);
// static const IconData angellist = const IconData(0xf209, fontFamily: _kFontFam);
// static const IconData cc = const IconData(0xf20a, fontFamily: _kFontFam);
// static const IconData shekel = const IconData(0xf20b, fontFamily: _kFontFam);
// static const IconData meanpath = const IconData(0xf20c, fontFamily: _kFontFam);
// static const IconData buysellads = const IconData(0xf20d, fontFamily: _kFontFam);
// static const IconData connectdevelop = const IconData(0xf20e, fontFamily: _kFontFam);
// static const IconData dashcube = const IconData(0xf210, fontFamily: _kFontFam);
// static const IconData forumbee = const IconData(0xf211, fontFamily: _kFontFam);
// static const IconData leanpub = const IconData(0xf212, fontFamily: _kFontFam);
// static const IconData sellsy = const IconData(0xf213, fontFamily: _kFontFam);
// static const IconData shirtsinbulk = const IconData(0xf214, fontFamily: _kFontFam);
// static const IconData simplybuilt = const IconData(0xf215, fontFamily: _kFontFam);
// static const IconData skyatlas = const IconData(0xf216, fontFamily: _kFontFam);
// static const IconData cart_plus = const IconData(0xf217, fontFamily: _kFontFam);
// static const IconData cart_arrow_down = const IconData(0xf218, fontFamily: _kFontFam);
// static const IconData diamond_1 = const IconData(0xf219, fontFamily: _kFontFam);
// static const IconData ship = const IconData(0xf21a, fontFamily: _kFontFam);
// static const IconData user_secret = const IconData(0xf21b, fontFamily: _kFontFam);
// static const IconData motorcycle_1 = const IconData(0xf21c, fontFamily: _kFontFam);
// static const IconData street_view = const IconData(0xf21d, fontFamily: _kFontFam);
// static const IconData heartbeat = const IconData(0xf21e, fontFamily: _kFontFam);
// static const IconData venus = const IconData(0xf221, fontFamily: _kFontFam);
// static const IconData mars = const IconData(0xf222, fontFamily: _kFontFam);
// static const IconData mercury = const IconData(0xf223, fontFamily: _kFontFam);
// static const IconData transgender = const IconData(0xf224, fontFamily: _kFontFam);
// static const IconData transgender_alt = const IconData(0xf225, fontFamily: _kFontFam);
// static const IconData venus_double = const IconData(0xf226, fontFamily: _kFontFam);
// static const IconData mars_double = const IconData(0xf227, fontFamily: _kFontFam);
// static const IconData venus_mars = const IconData(0xf228, fontFamily: _kFontFam);
// static const IconData mars_stroke = const IconData(0xf229, fontFamily: _kFontFam);
// static const IconData mars_stroke_v = const IconData(0xf22a, fontFamily: _kFontFam);
// static const IconData mars_stroke_h = const IconData(0xf22b, fontFamily: _kFontFam);
// static const IconData neuter = const IconData(0xf22c, fontFamily: _kFontFam);
// static const IconData genderless = const IconData(0xf22d, fontFamily: _kFontFam);
// static const IconData facebook_official = const IconData(0xf230, fontFamily: _kFontFam);
// static const IconData pinterest = const IconData(0xf231, fontFamily: _kFontFam);
// static const IconData whatsapp = const IconData(0xf232, fontFamily: _kFontFam);
// static const IconData server = const IconData(0xf233, fontFamily: _kFontFam);

// static const IconData user_times = const IconData(0xf235, fontFamily: _kFontFam);
// static const IconData bed = const IconData(0xf236, fontFamily: _kFontFam);
// static const IconData viacoin = const IconData(0xf237, fontFamily: _kFontFam);
// static const IconData train_1 = const IconData(0xf238, fontFamily: _kFontFam);
// static const IconData subway_1 = const IconData(0xf239, fontFamily: _kFontFam);
// static const IconData medium = const IconData(0xf23a, fontFamily: _kFontFam);
// static const IconData y_combinator = const IconData(0xf23b, fontFamily: _kFontFam);
// static const IconData optin_monster = const IconData(0xf23c, fontFamily: _kFontFam);
// static const IconData opencart = const IconData(0xf23d, fontFamily: _kFontFam);
// static const IconData expeditedssl = const IconData(0xf23e, fontFamily: _kFontFam);
// static const IconData battery_4 = const IconData(0xf240, fontFamily: _kFontFam);
// static const IconData battery_3 = const IconData(0xf241, fontFamily: _kFontFam);
// static const IconData battery_2 = const IconData(0xf242, fontFamily: _kFontFam);
// static const IconData battery_1 = const IconData(0xf243, fontFamily: _kFontFam);
// static const IconData battery_0 = const IconData(0xf244, fontFamily: _kFontFam);
// static const IconData mouse_pointer = const IconData(0xf245, fontFamily: _kFontFam);
// static const IconData i_cursor = const IconData(0xf246, fontFamily: _kFontFam);
// static const IconData object_group = const IconData(0xf247, fontFamily: _kFontFam);
// static const IconData object_ungroup = const IconData(0xf248, fontFamily: _kFontFam);
// static const IconData sticky_note = const IconData(0xf249, fontFamily: _kFontFam);
// static const IconData sticky_note_o = const IconData(0xf24a, fontFamily: _kFontFam);
// static const IconData cc_jcb = const IconData(0xf24b, fontFamily: _kFontFam);
// static const IconData cc_diners_club = const IconData(0xf24c, fontFamily: _kFontFam);
// static const IconData clone = const IconData(0xf24d, fontFamily: _kFontFam);
// static const IconData balance_scale = const IconData(0xf24e, fontFamily: _kFontFam);
// static const IconData hourglass_o = const IconData(0xf250, fontFamily: _kFontFam);
// static const IconData hourglass_1 = const IconData(0xf251, fontFamily: _kFontFam);
// static const IconData hourglass_2 = const IconData(0xf252, fontFamily: _kFontFam);
// static const IconData hourglass_3 = const IconData(0xf253, fontFamily: _kFontFam);
// static const IconData hourglass_4 = const IconData(0xf254, fontFamily: _kFontFam);
// static const IconData hand_grab_o = const IconData(0xf255, fontFamily: _kFontFam);
// static const IconData hand_paper_o = const IconData(0xf256, fontFamily: _kFontFam);
// static const IconData hand_scissors_o = const IconData(0xf257, fontFamily: _kFontFam);
// static const IconData hand_lizard_o = const IconData(0xf258, fontFamily: _kFontFam);
// static const IconData hand_spock_o = const IconData(0xf259, fontFamily: _kFontFam);
// static const IconData hand_pointer_o = const IconData(0xf25a, fontFamily: _kFontFam);
// static const IconData hand_peace_o = const IconData(0xf25b, fontFamily: _kFontFam);
// static const IconData trademark = const IconData(0xf25c, fontFamily: _kFontFam);
// static const IconData registered = const IconData(0xf25d, fontFamily: _kFontFam);
// static const IconData creative_commons = const IconData(0xf25e, fontFamily: _kFontFam);
// static const IconData gg = const IconData(0xf260, fontFamily: _kFontFam);
// static const IconData gg_circle = const IconData(0xf261, fontFamily: _kFontFam);
// static const IconData tripadvisor = const IconData(0xf262, fontFamily: _kFontFam);
// static const IconData odnoklassniki = const IconData(0xf263, fontFamily: _kFontFam);
// static const IconData odnoklassniki_square = const IconData(0xf264, fontFamily: _kFontFam);
// static const IconData get_pocket = const IconData(0xf265, fontFamily: _kFontFam);
// static const IconData wikipedia_w = const IconData(0xf266, fontFamily: _kFontFam);
// static const IconData safari = const IconData(0xf267, fontFamily: _kFontFam);
// static const IconData chrome_1 = const IconData(0xf268, fontFamily: _kFontFam);
// static const IconData firefox_1 = const IconData(0xf269, fontFamily: _kFontFam);
// static const IconData opera_1 = const IconData(0xf26a, fontFamily: _kFontFam);
// static const IconData internet_explorer = const IconData(0xf26b, fontFamily: _kFontFam);
// static const IconData television = const IconData(0xf26c, fontFamily: _kFontFam);
// static const IconData contao = const IconData(0xf26d, fontFamily: _kFontFam);
// static const IconData 500px = const IconData(0xf26e, fontFamily: _kFontFam);
// static const IconData amazon = const IconData(0xf270, fontFamily: _kFontFam);
// static const IconData calendar_plus_o = const IconData(0xf271, fontFamily: _kFontFam);
// static const IconData calendar_minus_o = const IconData(0xf272, fontFamily: _kFontFam);
// static const IconData calendar_times_o = const IconData(0xf273, fontFamily: _kFontFam);
// static const IconData calendar_check_o = const IconData(0xf274, fontFamily: _kFontFam);
// static const IconData industry = const IconData(0xf275, fontFamily: _kFontFam);
  static const IconData map_pin = const IconData(0xf276, fontFamily: _kFontFam);

// static const IconData map_signs = const IconData(0xf277, fontFamily: _kFontFam);
// static const IconData map_o = const IconData(0xf278, fontFamily: _kFontFam);
// static const IconData map_1 = const IconData(0xf279, fontFamily: _kFontFam);
// static const IconData commenting = const IconData(0xf27a, fontFamily: _kFontFam);
// static const IconData commenting_o = const IconData(0xf27b, fontFamily: _kFontFam);
// static const IconData houzz = const IconData(0xf27c, fontFamily: _kFontFam);
// static const IconData vimeo = const IconData(0xf27d, fontFamily: _kFontFam);
// static const IconData black_tie = const IconData(0xf27e, fontFamily: _kFontFam);
// static const IconData fonticons = const IconData(0xf280, fontFamily: _kFontFam);
// static const IconData reddit_alien = const IconData(0xf281, fontFamily: _kFontFam);
// static const IconData edge = const IconData(0xf282, fontFamily: _kFontFam);
// static const IconData credit_card_alt = const IconData(0xf283, fontFamily: _kFontFam);
// static const IconData codiepie = const IconData(0xf284, fontFamily: _kFontFam);
// static const IconData modx = const IconData(0xf285, fontFamily: _kFontFam);
// static const IconData fort_awesome = const IconData(0xf286, fontFamily: _kFontFam);
// static const IconData usb_1 = const IconData(0xf287, fontFamily: _kFontFam);
// static const IconData product_hunt = const IconData(0xf288, fontFamily: _kFontFam);
// static const IconData mixcloud = const IconData(0xf289, fontFamily: _kFontFam);
// static const IconData scribd = const IconData(0xf28a, fontFamily: _kFontFam);
// static const IconData pause_circle = const IconData(0xf28b, fontFamily: _kFontFam);
// static const IconData pause_circle_o = const IconData(0xf28c, fontFamily: _kFontFam);
// static const IconData stop_circle = const IconData(0xf28d, fontFamily: _kFontFam);
// static const IconData stop_circle_o = const IconData(0xf28e, fontFamily: _kFontFam);
// static const IconData shopping_bag = const IconData(0xf290, fontFamily: _kFontFam);
// static const IconData shopping_basket = const IconData(0xf291, fontFamily: _kFontFam);
// static const IconData hashtag = const IconData(0xf292, fontFamily: _kFontFam);
// static const IconData bluetooth = const IconData(0xf293, fontFamily: _kFontFam);
// static const IconData bluetooth_b = const IconData(0xf294, fontFamily: _kFontFam);
// static const IconData percent = const IconData(0xf295, fontFamily: _kFontFam);
// static const IconData gitlab = const IconData(0xf296, fontFamily: _kFontFam);
// static const IconData wpbeginner = const IconData(0xf297, fontFamily: _kFontFam);
// static const IconData wpforms = const IconData(0xf298, fontFamily: _kFontFam);
// static const IconData envira = const IconData(0xf299, fontFamily: _kFontFam);
// static const IconData universal_access = const IconData(0xf29a, fontFamily: _kFontFam);
// static const IconData wheelchair_alt = const IconData(0xf29b, fontFamily: _kFontFam);
// static const IconData question_circle_o = const IconData(0xf29c, fontFamily: _kFontFam);
// static const IconData blind = const IconData(0xf29d, fontFamily: _kFontFam);
// static const IconData audio_description = const IconData(0xf29e, fontFamily: _kFontFam);
// static const IconData volume_control_phone = const IconData(0xf2a0, fontFamily: _kFontFam);
// static const IconData braille = const IconData(0xf2a1, fontFamily: _kFontFam);
// static const IconData assistive_listening_systems = const IconData(0xf2a2, fontFamily: _kFontFam);
// static const IconData american_sign_language_interpreting = const IconData(0xf2a3, fontFamily: _kFontFam);
// static const IconData asl_interpreting = const IconData(0xf2a4, fontFamily: _kFontFam);
// static const IconData glide = const IconData(0xf2a5, fontFamily: _kFontFam);
// static const IconData glide_g = const IconData(0xf2a6, fontFamily: _kFontFam);
// static const IconData sign_language = const IconData(0xf2a7, fontFamily: _kFontFam);
// static const IconData low_vision = const IconData(0xf2a8, fontFamily: _kFontFam);
// static const IconData viadeo = const IconData(0xf2a9, fontFamily: _kFontFam);
// static const IconData viadeo_square = const IconData(0xf2aa, fontFamily: _kFontFam);
// static const IconData snapchat = const IconData(0xf2ab, fontFamily: _kFontFam);
// static const IconData snapchat_ghost = const IconData(0xf2ac, fontFamily: _kFontFam);
// static const IconData snapchat_square = const IconData(0xf2ad, fontFamily: _kFontFam);
// static const IconData pied_piper = const IconData(0xf2ae, fontFamily: _kFontFam);
// static const IconData first_order = const IconData(0xf2b0, fontFamily: _kFontFam);
// static const IconData yoast = const IconData(0xf2b1, fontFamily: _kFontFam);
// static const IconData themeisle = const IconData(0xf2b2, fontFamily: _kFontFam);
// static const IconData google_plus_circle = const IconData(0xf2b3, fontFamily: _kFontFam);
// static const IconData font_awesome = const IconData(0xf2b4, fontFamily: _kFontFam);
// static const IconData github_squared = const IconData(0xf300, fontFamily: _kFontFam);
// static const IconData twitter_squared = const IconData(0xf304, fontFamily: _kFontFam);
// static const IconData facebook_squared = const IconData(0xf308, fontFamily: _kFontFam);
// static const IconData linkedin_squared = const IconData(0xf30c, fontFamily: _kFontFam);r
//  static const IconData angle_up = const IconData(      0xf106, fontFamily: _kFontFam);
//  static const IconData angle_down = const IconData(      0xf107, fontFamily: _kFontFam);
  static const IconData map_o = const IconData(0xf278, fontFamily: _kFontFam);

//  static const IconData map_pin = const IconData(0xf276, fontFamily: _kFontFam);
  static const IconData credit_card = const IconData(
      0xec4d, fontFamily: _kFontFam);

  static const IconData star_1 = const IconData(0xebb9, fontFamily: _kFontFam);
  static const IconData star_empty_1 = const IconData(
      0xebba, fontFamily: _kFontFam);
  static const IconData star_half_1 = const IconData(
      0xebbb, fontFamily: _kFontFam);
  static const IconData list_numbered = const IconData(
      0xf0cb, fontFamily: _kFontFam);
  static const IconData list_alt = const IconData(
      0xec41, fontFamily: _kFontFam);
  static const IconData money = const IconData(0xf0d6, fontFamily: _kFontFam);

}
